[package]
name = "deadbeef" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Brad Urani <bradurani@gmail.com>"]

[dependencies]
rand = "0.3.12"
matches = "0.1.8"
itertools = "0.7.8"
[dependencies.shakmaty]
path = "../shakmaty"
