[package]
name = "deadbeef" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Brad Urani <bradurani@gmail.com>"]

[dependencies]
shakmaty = "0.11.2"
rand = "0.3.12"
matches = "0.1.8"
